// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqbyqtvaxjroakgnxlun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxYnlxdHZheGpyb2FrZ254bHVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MjgyNTUsImV4cCI6MjA3MjAwNDI1NX0.-maAL13IekgDe9K_Lfmvs8vg2nKBr06ew_EUcJ0c6DU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    // Keep client auth isolated from admin auth
    storageKey: 'sb-client-auth',
    persistSession: true,
    autoRefreshToken: true,
  }
});
